/*****************************************************************************
 *
 * 
 * Copyright 2016 - 2019 CHENGDU HAIGUANG IC DESIGN CO., LTD. All Rights Reserved.
 * 
 * HYGON is granting you permission to use this software (the Materials)
 * pursuant to the terms and conditions of your Software License Agreement
 * with HYGON.  This header does *NOT* give you permission to use the Materials
 * or any rights under HYGON's intellectual property.  Your use of any portion
 * of these Materials shall constitute your acceptance of those terms and
 * conditions.  If you do not agree to the terms and conditions of the Software
 * License Agreement, please do not use any portion of these Materials.
 * 
 * CONFIDENTIALITY:  The Materials and all other information, identified as
 * confidential and provided to you by HYGON shall be kept confidential in
 * accordance with the terms and conditions of the Software License Agreement.
 * 
 * LIMITATION OF LIABILITY: THE MATERIALS AND ANY OTHER RELATED INFORMATION
 * PROVIDED TO YOU BY HYGON ARE PROVIDED "AS IS" WITHOUT ANY EXPRESS OR IMPLIED
 * WARRANTY OF ANY KIND, INCLUDING BUT NOT LIMITED TO WARRANTIES OF
 * MERCHANTABILITY, NONINFRINGEMENT, TITLE, FITNESS FOR ANY PARTICULAR PURPOSE,
 * OR WARRANTIES ARISING FROM CONDUCT, COURSE OF DEALING, OR USAGE OF TRADE.
 * IN NO EVENT SHALL HYGON OR ITS LICENSORS BE LIABLE FOR ANY DAMAGES WHATSOEVER
 * (INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOSS OF PROFITS, BUSINESS
 * INTERRUPTION, OR LOSS OF INFORMATION) ARISING OUT OF HYGON'S NEGLIGENCE,
 * GROSS NEGLIGENCE, THE USE OF OR INABILITY TO USE THE MATERIALS OR ANY OTHER
 * RELATED INFORMATION PROVIDED TO YOU BY HYGON, EVEN IF HYGON HAS BEEN ADVISED OF
 * THE POSSIBILITY OF SUCH DAMAGES.  BECAUSE SOME JURISDICTIONS PROHIBIT THE
 * EXCLUSION OR LIMITATION OF LIABILITY FOR CONSEQUENTIAL OR INCIDENTAL DAMAGES,
 * THE ABOVE LIMITATION MAY NOT APPLY TO YOU.
 * 
 * HYGON does not assume any responsibility for any errors which may appear in
 * the Materials or any other related information provided to you by HYGON, or
 * result from use of the Materials or any related information.
 * 
 * You agree that you will not reverse engineer or decompile the Materials.
 * 
 * NO SUPPORT OBLIGATION: HYGON is not obligated to furnish, support, or make any
 * further information, software, technical information, know-how, or show-how
 * available to you.  Additionally, HYGON retains the right to modify the
 * Materials at any time, without notice, and is not obligated to provide such
 * modified Materials to you.
 * 
 * AMD GRANT HYGON DECLARATION: ADVANCED MICRO DEVICES, INC.(AMD) granted HYGON has
 * the right to redistribute HYGON's Agesa version to BIOS Vendors and HYGON has
 * the right to make the modified version available for use with HYGON's PRODUCT.
 *
 ***************************************************************************/


//This file is auto generated, don't edit it manually

#ifndef _APCB_AUTOGEN_ZP_H_
#define _APCB_AUTOGEN_ZP_H_


//
// CBS CMN APCB Tokens
//
#ifndef APCB_TOKEN_CBS_CMN_BEGIN
  #define APCB_TOKEN_CBS_CMN_BEGIN 0x0000
#endif

#ifndef APCB_TOKEN_CBS_DF_CMN_GMI_ENCRYPTION
  #define APCB_TOKEN_CBS_DF_CMN_GMI_ENCRYPTION 0x0001
#endif

#ifndef APCB_TOKEN_CBS_DF_CMN_X_GMI_ENCRYPTION
  #define APCB_TOKEN_CBS_DF_CMN_X_GMI_ENCRYPTION 0x0002
#endif

#ifndef APCB_TOKEN_CBS_DF_CMN_CC6_MEM_ENCRYPTION
  #define APCB_TOKEN_CBS_DF_CMN_CC6_MEM_ENCRYPTION 0x0003
#endif

#ifndef APCB_TOKEN_CBS_DF_CMN_CC6_ALLOCATION_SCHEME
  #define APCB_TOKEN_CBS_DF_CMN_CC6_ALLOCATION_SCHEME 0x0004
#endif

#ifndef APCB_TOKEN_CBS_DF_CMN_SYS_PROBE_FILTER
  #define APCB_TOKEN_CBS_DF_CMN_SYS_PROBE_FILTER 0x0005
#endif

#ifndef APCB_TOKEN_CBS_DF_CMN_MEM_INTLV
  #define APCB_TOKEN_CBS_DF_CMN_MEM_INTLV 0x0006
#endif

#ifndef APCB_TOKEN_CBS_DF_CMN_MEM_INTLV_SIZE
  #define APCB_TOKEN_CBS_DF_CMN_MEM_INTLV_SIZE 0x0007
#endif

#ifndef APCB_TOKEN_CBS_DF_CMN_CHNL_INTLV_HASH
  #define APCB_TOKEN_CBS_DF_CMN_CHNL_INTLV_HASH 0x0008
#endif

#ifndef APCB_TOKEN_CBS_CMN_MEM_MAPPING_BANK_INTERLEAVE_DDR4
  #define APCB_TOKEN_CBS_CMN_MEM_MAPPING_BANK_INTERLEAVE_DDR4 0x0009
#endif

#ifndef APCB_TOKEN_CBS_CMN_MEM_CTRLLER_BANK_GROUP_SWAP_DDR4
  #define APCB_TOKEN_CBS_CMN_MEM_CTRLLER_BANK_GROUP_SWAP_DDR4 0x000A
#endif

#ifndef APCB_TOKEN_CBS_CMN_MEM_CTRLLER_BANK_SWIZZLE_DDR4
  #define APCB_TOKEN_CBS_CMN_MEM_CTRLLER_BANK_SWIZZLE_DDR4 0x000B
#endif

#ifndef APCB_TOKEN_CBS_CMN_MEM_ADDRESS_HASHING_DDR4
  #define APCB_TOKEN_CBS_CMN_MEM_ADDRESS_HASHING_DDR4 0x000C
#endif

#ifndef APCB_TOKEN_CBS_CMN_MEM_SPEED_DDR4
  #define APCB_TOKEN_CBS_CMN_MEM_SPEED_DDR4 0x000D
#endif

#ifndef APCB_TOKEN_CBS_CMN_MEM_TIMING_TCL_DDR4
  #define APCB_TOKEN_CBS_CMN_MEM_TIMING_TCL_DDR4 0x000E
#endif

#ifndef APCB_TOKEN_CBS_CMN_MEM_TIMING_TRCDRD_DDR4
  #define APCB_TOKEN_CBS_CMN_MEM_TIMING_TRCDRD_DDR4 0x000F
#endif

#ifndef APCB_TOKEN_CBS_CMN_MEM_TIMING_TRCDWR_DDR4
  #define APCB_TOKEN_CBS_CMN_MEM_TIMING_TRCDWR_DDR4 0x0010
#endif

#ifndef APCB_TOKEN_CBS_CMN_MEM_TIMING_TRP_DDR4
  #define APCB_TOKEN_CBS_CMN_MEM_TIMING_TRP_DDR4 0x0011
#endif

#ifndef APCB_TOKEN_CBS_CMN_MEM_TIMING_TRAS_DDR4
  #define APCB_TOKEN_CBS_CMN_MEM_TIMING_TRAS_DDR4 0x0012
#endif

#ifndef APCB_TOKEN_CBS_CMN_MEM_DATA_POISONING_DDR4
  #define APCB_TOKEN_CBS_CMN_MEM_DATA_POISONING_DDR4 0x0013
#endif

#ifndef APCB_TOKEN_CBS_CMN_MEM_ADDRESS_HASH_BANK_DDR4
  #define APCB_TOKEN_CBS_CMN_MEM_ADDRESS_HASH_BANK_DDR4 0x0014
#endif

#ifndef APCB_TOKEN_CBS_CMN_MEM_ADDRESS_HASH_CS_DDR4
  #define APCB_TOKEN_CBS_CMN_MEM_ADDRESS_HASH_CS_DDR4 0x0015
#endif

#ifndef APCB_TOKEN_CBS_CMN_MEM_TSME_DDR4
  #define APCB_TOKEN_CBS_CMN_MEM_TSME_DDR4 0x0016
#endif

#ifndef APCB_TOKEN_CBS_CMN_MEM_OVERCLOCK_DDR4
  #define APCB_TOKEN_CBS_CMN_MEM_OVERCLOCK_DDR4 0x0017
#endif

#ifndef APCB_TOKEN_CBS_CMN_GNB_GFX_UMA_MODE
  #define APCB_TOKEN_CBS_CMN_GNB_GFX_UMA_MODE 0x0018
#endif

#ifndef APCB_TOKEN_CBS_CMN_GNB_GFX_UMA_VERSION
  #define APCB_TOKEN_CBS_CMN_GNB_GFX_UMA_VERSION 0x0019
#endif

#ifndef APCB_TOKEN_CBS_CMN_GNB_GFX_DISPLAY_RESOLUTION
  #define APCB_TOKEN_CBS_CMN_GNB_GFX_DISPLAY_RESOLUTION 0x001A
#endif

#ifndef APCB_TOKEN_CBS_CMN_GNB_GFX_UMA_FRAME_BUFFER_SIZE
  #define APCB_TOKEN_CBS_CMN_GNB_GFX_UMA_FRAME_BUFFER_SIZE 0x001B
#endif

#ifndef APCB_TOKEN_CBS_CMN_CPU_SEV_ASID_SPACE_LIMIT
  #define APCB_TOKEN_CBS_CMN_CPU_SEV_ASID_SPACE_LIMIT 0x001C
#endif

#ifndef APCB_TOKEN_CBS_CMN_MEM_SPD_READ_OPTIMIZATION_DDR4
  #define APCB_TOKEN_CBS_CMN_MEM_SPD_READ_OPTIMIZATION_DDR4 0x001D
#endif

#ifndef APCB_TOKEN_CBS_CMN_MEM_MBIST_EN
  #define APCB_TOKEN_CBS_CMN_MEM_MBIST_EN 0x001E
#endif

#ifndef APCB_TOKEN_CBS_CMN_MEM_MBIST_SUB_TEST
  #define APCB_TOKEN_CBS_CMN_MEM_MBIST_SUB_TEST 0x001F
#endif

#ifndef APCB_TOKEN_CBS_DF_CMN_MEM_CLEAR
  #define APCB_TOKEN_CBS_DF_CMN_MEM_CLEAR 0x0020
#endif

#ifndef APCB_TOKEN_CBS_CMN_MEM_TIMING_TRC_CTRL_DDR4
  #define APCB_TOKEN_CBS_CMN_MEM_TIMING_TRC_CTRL_DDR4 0x0021
#endif

#ifndef APCB_TOKEN_CBS_CMN_MEM_TIMING_TRC_DDR4
  #define APCB_TOKEN_CBS_CMN_MEM_TIMING_TRC_DDR4 0x0022
#endif

#ifndef APCB_TOKEN_CBS_CMN_MEM_TIMING_TRRD_S_DDR4
  #define APCB_TOKEN_CBS_CMN_MEM_TIMING_TRRD_S_DDR4 0x0023
#endif

#ifndef APCB_TOKEN_CBS_CMN_MEM_TIMING_TRRD_L_DDR4
  #define APCB_TOKEN_CBS_CMN_MEM_TIMING_TRRD_L_DDR4 0x0024
#endif

#ifndef APCB_TOKEN_CBS_CMN_MEM_TIMING_TFAW_CTRL_DDR4
  #define APCB_TOKEN_CBS_CMN_MEM_TIMING_TFAW_CTRL_DDR4 0x0025
#endif

#ifndef APCB_TOKEN_CBS_CMN_MEM_TIMING_TFAW_DDR4
  #define APCB_TOKEN_CBS_CMN_MEM_TIMING_TFAW_DDR4 0x0026
#endif

#ifndef APCB_TOKEN_CBS_CMN_MEM_TIMING_TWTR_S_DDR4
  #define APCB_TOKEN_CBS_CMN_MEM_TIMING_TWTR_S_DDR4 0x0027
#endif

#ifndef APCB_TOKEN_CBS_CMN_MEM_TIMING_TWTR_L_DDR4
  #define APCB_TOKEN_CBS_CMN_MEM_TIMING_TWTR_L_DDR4 0x0028
#endif

#ifndef APCB_TOKEN_CBS_CMN_MEM_TIMING_TWR_CTRL_DDR4
  #define APCB_TOKEN_CBS_CMN_MEM_TIMING_TWR_CTRL_DDR4 0x0029
#endif

#ifndef APCB_TOKEN_CBS_CMN_MEM_TIMING_TWR_DDR4
  #define APCB_TOKEN_CBS_CMN_MEM_TIMING_TWR_DDR4 0x002A
#endif

#ifndef APCB_TOKEN_CBS_CMN_MEM_TIMING_TRCPAGE_CTRL_DDR4
  #define APCB_TOKEN_CBS_CMN_MEM_TIMING_TRCPAGE_CTRL_DDR4 0x002B
#endif

#ifndef APCB_TOKEN_CBS_CMN_MEM_TIMING_TRCPAGE_DDR4
  #define APCB_TOKEN_CBS_CMN_MEM_TIMING_TRCPAGE_DDR4 0x002C
#endif

#ifndef APCB_TOKEN_CBS_CMN_MEM_TIMING_TRDRD_SC_L_CTRL_DDR4
  #define APCB_TOKEN_CBS_CMN_MEM_TIMING_TRDRD_SC_L_CTRL_DDR4 0x002D
#endif

#ifndef APCB_TOKEN_CBS_CMN_MEM_TIMING_TRDRD_SC_L_DDR4
  #define APCB_TOKEN_CBS_CMN_MEM_TIMING_TRDRD_SC_L_DDR4 0x002E
#endif

#ifndef APCB_TOKEN_CBS_CMN_MEM_TIMING_TWRWR_SC_L_CTRL_DDR4
  #define APCB_TOKEN_CBS_CMN_MEM_TIMING_TWRWR_SC_L_CTRL_DDR4 0x002F
#endif

#ifndef APCB_TOKEN_CBS_CMN_MEM_TIMING_TWRWR_SC_L_DDR4
  #define APCB_TOKEN_CBS_CMN_MEM_TIMING_TWRWR_SC_L_DDR4 0x0030
#endif

#ifndef APCB_TOKEN_CBS_CMN_MEM_TIMING_TRFC_CTRL_DDR4
  #define APCB_TOKEN_CBS_CMN_MEM_TIMING_TRFC_CTRL_DDR4 0x0031
#endif

#ifndef APCB_TOKEN_CBS_CMN_MEM_TIMING_TRFC_DDR4
  #define APCB_TOKEN_CBS_CMN_MEM_TIMING_TRFC_DDR4 0x0032
#endif

#ifndef APCB_TOKEN_CBS_CMN_MEM_TIMING_TRFC2_CTRL_DDR4
  #define APCB_TOKEN_CBS_CMN_MEM_TIMING_TRFC2_CTRL_DDR4 0x0033
#endif

#ifndef APCB_TOKEN_CBS_CMN_MEM_TIMING_TRFC2_DDR4
  #define APCB_TOKEN_CBS_CMN_MEM_TIMING_TRFC2_DDR4 0x0034
#endif

#ifndef APCB_TOKEN_CBS_CMN_MEM_TIMING_TRFC4_CTRL_DDR4
  #define APCB_TOKEN_CBS_CMN_MEM_TIMING_TRFC4_CTRL_DDR4 0x0035
#endif

#ifndef APCB_TOKEN_CBS_CMN_MEM_TIMING_TRFC4_DDR4
  #define APCB_TOKEN_CBS_CMN_MEM_TIMING_TRFC4_DDR4 0x0036
#endif

#ifndef APCB_TOKEN_CBS_CMN_MEM_OVERCLOCK_FAIL_CNT
  #define APCB_TOKEN_CBS_CMN_MEM_OVERCLOCK_FAIL_CNT 0x0037
#endif

#ifndef APCB_TOKEN_CBS_CMN_MEM_CTRLLER_PROC_ODT_DDR4
  #define APCB_TOKEN_CBS_CMN_MEM_CTRLLER_PROC_ODT_DDR4 0x0038
#endif

#ifndef APCB_TOKEN_CBS_CMN_MEM_TIMING_TRDRD_SC_DDR4
  #define APCB_TOKEN_CBS_CMN_MEM_TIMING_TRDRD_SC_DDR4 0x0039
#endif

#ifndef APCB_TOKEN_CBS_CMN_MEM_TIMING_TRDRD_SD_DDR4
  #define APCB_TOKEN_CBS_CMN_MEM_TIMING_TRDRD_SD_DDR4 0x003A
#endif

#ifndef APCB_TOKEN_CBS_CMN_MEM_TIMING_TRDRD_DD_DDR4
  #define APCB_TOKEN_CBS_CMN_MEM_TIMING_TRDRD_DD_DDR4 0x003B
#endif

#ifndef APCB_TOKEN_CBS_CMN_MEM_TIMING_TWRWR_SC_DDR4
  #define APCB_TOKEN_CBS_CMN_MEM_TIMING_TWRWR_SC_DDR4 0x003C
#endif

#ifndef APCB_TOKEN_CBS_CMN_MEM_TIMING_TWRWR_SD_DDR4
  #define APCB_TOKEN_CBS_CMN_MEM_TIMING_TWRWR_SD_DDR4 0x003D
#endif

#ifndef APCB_TOKEN_CBS_CMN_MEM_TIMING_TWRWR_DD_DDR4
  #define APCB_TOKEN_CBS_CMN_MEM_TIMING_TWRWR_DD_DDR4 0x003E
#endif

#ifndef APCB_TOKEN_CBS_CMN_MEM_TIMING_TRDWR_DDR4
  #define APCB_TOKEN_CBS_CMN_MEM_TIMING_TRDWR_DDR4 0x003F
#endif

#ifndef APCB_TOKEN_CBS_CMN_MEM_TIMING_TWRRD_DDR4
  #define APCB_TOKEN_CBS_CMN_MEM_TIMING_TWRRD_DDR4 0x0040
#endif

#ifndef APCB_TOKEN_CBS_CMN_MEM_TIMING_TRTP_DDR4
  #define APCB_TOKEN_CBS_CMN_MEM_TIMING_TRTP_DDR4 0x0041
#endif

#ifndef APCB_TOKEN_CBS_CMN_MEM_TIMING_TCWL_DDR4
  #define APCB_TOKEN_CBS_CMN_MEM_TIMING_TCWL_DDR4 0x0042
#endif

#ifndef APCB_TOKEN_CBS_CMN_MEM_DATA_BUS_CONFIG_CTL_DDR4
  #define APCB_TOKEN_CBS_CMN_MEM_DATA_BUS_CONFIG_CTL_DDR4 0x0043
#endif

#ifndef APCB_TOKEN_CBS_CMN_MEM_CTRLLER_RTT_NOM_DDR4
  #define APCB_TOKEN_CBS_CMN_MEM_CTRLLER_RTT_NOM_DDR4 0x0044
#endif

#ifndef APCB_TOKEN_CBS_CMN_MEM_CTRLLER_RTT_WR_DDR4
  #define APCB_TOKEN_CBS_CMN_MEM_CTRLLER_RTT_WR_DDR4 0x0045
#endif

#ifndef APCB_TOKEN_CBS_CMN_MEM_CTRLLER_RTT_PARK_DDR4
  #define APCB_TOKEN_CBS_CMN_MEM_CTRLLER_RTT_PARK_DDR4 0x0046
#endif

#ifndef APCB_TOKEN_CBS_CMN_MEM_TIMING_TCKE_DDR4
  #define APCB_TOKEN_CBS_CMN_MEM_TIMING_TCKE_DDR4 0x0047
#endif

#ifndef APCB_TOKEN_CBS_CMN_MEM_CTRLLER_DATA_SCRAMBLE_DDR4
  #define APCB_TOKEN_CBS_CMN_MEM_CTRLLER_DATA_SCRAMBLE_DDR4 0x0048
#endif

#ifndef APCB_TOKEN_CBS_CMN_CLDO_VDDP_CTL
  #define APCB_TOKEN_CBS_CMN_CLDO_VDDP_CTL 0x0049
#endif

#ifndef APCB_TOKEN_CBS_CMN_CLDOVDD_PVOLTAGE
  #define APCB_TOKEN_CBS_CMN_CLDOVDD_PVOLTAGE 0x004A
#endif

#ifndef APCB_TOKEN_CBS_CMN_MEM_CTRLLER2_T_MODE_DDR4
  #define APCB_TOKEN_CBS_CMN_MEM_CTRLLER2_T_MODE_DDR4 0x004B
#endif

#ifndef APCB_TOKEN_CBS_CMN_MEM_GEAR_DOWN_MODE_DDR4
  #define APCB_TOKEN_CBS_CMN_MEM_GEAR_DOWN_MODE_DDR4 0x004C
#endif

#ifndef APCB_TOKEN_CBS_CMN_MEM_MBIST_AGGRESSORS
  #define APCB_TOKEN_CBS_CMN_MEM_MBIST_AGGRESSORS 0x004D
#endif

#ifndef APCB_TOKEN_CBS_CMN_MEM_MBIST_PER_BIT_SLAVE_DIE_REPORT
  #define APCB_TOKEN_CBS_CMN_MEM_MBIST_PER_BIT_SLAVE_DIE_REPORT 0x004E
#endif

#ifndef APCB_TOKEN_CBS_CMN_MEM_CTRLLER_PWR_DN_EN_DDR4
  #define APCB_TOKEN_CBS_CMN_MEM_CTRLLER_PWR_DN_EN_DDR4 0x004F
#endif

#ifndef APCB_TOKEN_CBS_CMN_MEM_MBIST_PER_BIT_SLAVE_DIE_REPORTING
  #define APCB_TOKEN_CBS_CMN_MEM_MBIST_PER_BIT_SLAVE_DIE_REPORTING 0x0050
#endif

#ifndef APCB_TOKEN_CBS_CMN_BIOS_SPI_SPEED_MODE
  #define APCB_TOKEN_CBS_CMN_BIOS_SPI_SPEED_MODE 0x0052
#endif

#ifndef APCB_TOKEN_CBS_CMN_AVS_CONTROL
  #define APCB_TOKEN_CBS_CMN_AVS_CONTROL 0x5D
#endif

#ifndef APCB_TOKEN_CBS_CMN_END
  #define APCB_TOKEN_CBS_CMN_END 0x005E
#endif

#ifndef APCB_TOKEN_CBS_CMN_LIMIT
  #define APCB_TOKEN_CBS_CMN_LIMIT 0x1FFF
#endif


//
// CBS DBG APCB Tokens
//
#ifndef APCB_TOKEN_CBS_DBG_BEGIN
  #define APCB_TOKEN_CBS_DBG_BEGIN 0x0000
#endif

#ifndef APCB_TOKEN_CBS_DF_DBG_CORE_MSTR_REQ_ORDERING
  #define APCB_TOKEN_CBS_DF_DBG_CORE_MSTR_REQ_ORDERING 0x0001
#endif

#ifndef APCB_TOKEN_CBS_DF_DBG_IO_MSTR_REQ_ORDERING
  #define APCB_TOKEN_CBS_DF_DBG_IO_MSTR_REQ_ORDERING 0x0002
#endif

#ifndef APCB_TOKEN_CBS_DF_DBG_MEM_CANCEL_DIS
  #define APCB_TOKEN_CBS_DF_DBG_MEM_CANCEL_DIS 0x0003
#endif

#ifndef APCB_TOKEN_CBS_DF_DBG_MIG_PRB_DIS
  #define APCB_TOKEN_CBS_DF_DBG_MIG_PRB_DIS 0x0004
#endif

#ifndef APCB_TOKEN_CBS_DF_DBG_STOP_ON_SPF_ERROR
  #define APCB_TOKEN_CBS_DF_DBG_STOP_ON_SPF_ERROR 0x0005
#endif

#ifndef APCB_TOKEN_CBS_DF_DBG_TCDX_BYPASS_DIS
  #define APCB_TOKEN_CBS_DF_DBG_TCDX_BYPASS_DIS 0x0006
#endif

#ifndef APCB_TOKEN_CBS_DF_DBG_F1F_FETCH_PRB_RMT
  #define APCB_TOKEN_CBS_DF_DBG_F1F_FETCH_PRB_RMT 0x0007
#endif

#ifndef APCB_TOKEN_CBS_DF_DBG_F1F_FETCH_PRB_LCL
  #define APCB_TOKEN_CBS_DF_DBG_F1F_FETCH_PRB_LCL 0x0008
#endif

#ifndef APCB_TOKEN_CBS_DF_DBG_F1F_FETCH_PRB_TARGET
  #define APCB_TOKEN_CBS_DF_DBG_F1F_FETCH_PRB_TARGET 0x0009
#endif

#ifndef APCB_TOKEN_CBS_DF_DBG_SPF_WAY_DIS
  #define APCB_TOKEN_CBS_DF_DBG_SPF_WAY_DIS 0x000A
#endif

#ifndef APCB_TOKEN_CBS_DF_DBG_IO_REQ_BUS_LOCK_CTRL
  #define APCB_TOKEN_CBS_DF_DBG_IO_REQ_BUS_LOCK_CTRL 0x000B
#endif

#ifndef APCB_TOKEN_CBS_DF_DBG_IOM_PERF_MON_PRB_RSP
  #define APCB_TOKEN_CBS_DF_DBG_IOM_PERF_MON_PRB_RSP 0x000C
#endif

#ifndef APCB_TOKEN_CBS_DF_DBG_IOM_PERF_MON_TGT_SEL
  #define APCB_TOKEN_CBS_DF_DBG_IOM_PERF_MON_TGT_SEL 0x000D
#endif

#ifndef APCB_TOKEN_CBS_DF_DBG_WDT_CTRL
  #define APCB_TOKEN_CBS_DF_DBG_WDT_CTRL 0x000E
#endif

#ifndef APCB_TOKEN_CBS_DF_DBG_CAKE_REQ_ADDR_COMPRESSION
  #define APCB_TOKEN_CBS_DF_DBG_CAKE_REQ_ADDR_COMPRESSION 0x000F
#endif

#ifndef APCB_TOKEN_CBS_DF_DBG_CAKE_DATA_COMPRESSION
  #define APCB_TOKEN_CBS_DF_DBG_CAKE_DATA_COMPRESSION 0x0010
#endif

#ifndef APCB_TOKEN_CBS_DF_DBG_CAKE_RSP_CMD_PACKING
  #define APCB_TOKEN_CBS_DF_DBG_CAKE_RSP_CMD_PACKING 0x0011
#endif

#ifndef APCB_TOKEN_CBS_DF_DBG_CAKE_PRB_COMBINING
  #define APCB_TOKEN_CBS_DF_DBG_CAKE_PRB_COMBINING 0x0012
#endif

#ifndef APCB_TOKEN_CBS_DF_DBG_CAKE_IO_ADDR_COMP_BIT
  #define APCB_TOKEN_CBS_DF_DBG_CAKE_IO_ADDR_COMP_BIT 0x0013
#endif

#ifndef APCB_TOKEN_CBS_DF_DBG_IO_BUS_LOCK_INV_DIS
  #define APCB_TOKEN_CBS_DF_DBG_IO_BUS_LOCK_INV_DIS 0x0014
#endif

#ifndef APCB_TOKEN_CBS_DF_DBG_PIE_PRQ_BCST_LIMIT
  #define APCB_TOKEN_CBS_DF_DBG_PIE_PRQ_BCST_LIMIT 0x0015
#endif

#ifndef APCB_TOKEN_CBS_DF_DBG_LMT_MAX_IO_REQ_MASTER
  #define APCB_TOKEN_CBS_DF_DBG_LMT_MAX_IO_REQ_MASTER 0x0016
#endif

#ifndef APCB_TOKEN_CBS_DF_DBG_LMT_MAX_IO_REQ_LIMIT
  #define APCB_TOKEN_CBS_DF_DBG_LMT_MAX_IO_REQ_LIMIT 0x0017
#endif

#ifndef APCB_TOKEN_CBS_DF_DBG_IOS_RSP_BYPASS_CTRL
  #define APCB_TOKEN_CBS_DF_DBG_IOS_RSP_BYPASS_CTRL 0x0018
#endif

#ifndef APCB_TOKEN_CBS_DF_DBG_CAKE_BYPASS_CTRL
  #define APCB_TOKEN_CBS_DF_DBG_CAKE_BYPASS_CTRL 0x0019
#endif

#ifndef APCB_TOKEN_CBS_DF_DBG_CS_BYPASS_CTRL
  #define APCB_TOKEN_CBS_DF_DBG_CS_BYPASS_CTRL 0x001A
#endif

#ifndef APCB_TOKEN_CBS_DF_DBG_TGT_START_CTRL
  #define APCB_TOKEN_CBS_DF_DBG_TGT_START_CTRL 0x001B
#endif

#ifndef APCB_TOKEN_CBS_DF_DBG_LINK_ERR_INJ
  #define APCB_TOKEN_CBS_DF_DBG_LINK_ERR_INJ 0x001C
#endif

#ifndef APCB_TOKEN_CBS_DF_DBG_VC8_TRACING_TOK_ALLOC
  #define APCB_TOKEN_CBS_DF_DBG_VC8_TRACING_TOK_ALLOC 0x001D
#endif

#ifndef APCB_TOKEN_CBS_DF_DBG_VC8_TRACING_REQ_CS
  #define APCB_TOKEN_CBS_DF_DBG_VC8_TRACING_REQ_CS 0x001E
#endif

#ifndef APCB_TOKEN_CBS_DF_DBG_VC8_TRACING_REQ_IOMS
  #define APCB_TOKEN_CBS_DF_DBG_VC8_TRACING_REQ_IOMS 0x001F
#endif

#ifndef APCB_TOKEN_CBS_DF_DBG_VC8_TRACING_CSQ
  #define APCB_TOKEN_CBS_DF_DBG_VC8_TRACING_CSQ 0x0020
#endif

#ifndef APCB_TOKEN_CBS_DF_DBG_VC8_TRACING_RSP_IOMS
  #define APCB_TOKEN_CBS_DF_DBG_VC8_TRACING_RSP_IOMS 0x0021
#endif

#ifndef APCB_TOKEN_CBS_DF_DBG_VC8_TRACING_RSP_TCDX
  #define APCB_TOKEN_CBS_DF_DBG_VC8_TRACING_RSP_TCDX 0x0022
#endif

#ifndef APCB_TOKEN_CBS_DF_DBG_REDUCE_CREDITS_REQ
  #define APCB_TOKEN_CBS_DF_DBG_REDUCE_CREDITS_REQ 0x0023
#endif

#ifndef APCB_TOKEN_CBS_DF_DBG_REDUCE_CREDITS_PRB
  #define APCB_TOKEN_CBS_DF_DBG_REDUCE_CREDITS_PRB 0x0024
#endif

#ifndef APCB_TOKEN_CBS_DF_DBG_REDUCE_CREDITS_RSP
  #define APCB_TOKEN_CBS_DF_DBG_REDUCE_CREDITS_RSP 0x0025
#endif

#ifndef APCB_TOKEN_CBS_DF_DBG_LOAD_STEP_CTRL_DIS
  #define APCB_TOKEN_CBS_DF_DBG_LOAD_STEP_CTRL_DIS 0x0026
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_TIMING_ENFORCE_FREQ_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_TIMING_ENFORCE_FREQ_DDR4 0x0027
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_TIMING_CTL_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_TIMING_CTL_DDR4 0x0028
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_SPEED_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_SPEED_DDR4 0x0029
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_TIMING_UCLK_DIV1_M0_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_TIMING_UCLK_DIV1_M0_DDR4 0x002A
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_TIMING_UCLK_DIV1_M1_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_TIMING_UCLK_DIV1_M1_DDR4 0x002B
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_TIMING_UCLK_DIV1_M2_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_TIMING_UCLK_DIV1_M2_DDR4 0x002C
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_TIMING_UCLK_DIV1_M3_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_TIMING_UCLK_DIV1_M3_DDR4 0x002D
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_TIMING_TCL_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_TIMING_TCL_DDR4 0x002E
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_TIMING_TRCDRD_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_TIMING_TRCDRD_DDR4 0x002F
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_TIMING_TRCDWR_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_TIMING_TRCDWR_DDR4 0x0030
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_TIMING_TRP_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_TIMING_TRP_DDR4 0x0031
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_TIMING_TRTP_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_TIMING_TRTP_DDR4 0x0032
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_TIMING_TRAS_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_TIMING_TRAS_DDR4 0x0033
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_TIMING_TRRD_L_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_TIMING_TRRD_L_DDR4 0x0034
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_TIMING_TRRD_S_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_TIMING_TRRD_S_DDR4 0x0035
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_TIMING_TRC_CTL_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_TIMING_TRC_CTL_DDR4 0x0036
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_TIMING_TRC_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_TIMING_TRC_DDR4 0x0037
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_TIMING_TRDWR_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_TIMING_TRDWR_DDR4 0x0038
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_TIMING_TWRRD_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_TIMING_TWRRD_DDR4 0x0039
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_TIMING_TWTR_L_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_TIMING_TWTR_L_DDR4 0x003A
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_TIMING_TWTR_S_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_TIMING_TWTR_S_DDR4 0x003B
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_TIMING_TWRWR_SC_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_TIMING_TWRWR_SC_DDR4 0x003C
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_TIMING_TWRWR_SD_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_TIMING_TWRWR_SD_DDR4 0x003D
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_TIMING_TWRWR_DD_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_TIMING_TWRWR_DD_DDR4 0x003E
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_TIMING_TRDRD_SC_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_TIMING_TRDRD_SC_DDR4 0x003F
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_TIMING_TRDRD_SD_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_TIMING_TRDRD_SD_DDR4 0x0040
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_TIMING_TRDRD_DD_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_TIMING_TRDRD_DD_DDR4 0x0041
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_TIMING_TREF_CTL_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_TIMING_TREF_CTL_DDR4 0x0042
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_TIMING_TREF_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_TIMING_TREF_DDR4 0x0043
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_TIMING_TRWT_WB_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_TIMING_TRWT_WB_DDR4 0x0044
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_TIMING_TRFC0_CTL_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_TIMING_TRFC0_CTL_DDR4 0x0045
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_TIMING_TRFC0_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_TIMING_TRFC0_DDR4 0x0046
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_TIMING_TRFC1_CTL_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_TIMING_TRFC1_CTL_DDR4 0x0047
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_TIMING_TRFC1_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_TIMING_TRFC1_DDR4 0x0048
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_TIMING_TCKSRX_CTL_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_TIMING_TCKSRX_CTL_DDR4 0x0049
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_TIMING_TCKSRX_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_TIMING_TCKSRX_DDR4 0x004A
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_TIMING_TCKSRE_CTL_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_TIMING_TCKSRE_CTL_DDR4 0x004B
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_TIMING_TCKSRE_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_TIMING_TCKSRE_DDR4 0x004C
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_TIMING_TPD_CTL_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_TIMING_TPD_CTL_DDR4 0x004D
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_TIMING_TPD_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_TIMING_TPD_DDR4 0x004E
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_CTRLLER_ADDR_CMD_TRI_EN_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_CTRLLER_ADDR_CMD_TRI_EN_DDR4 0x004F
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_CTRLLER2_T_MODE_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_CTRLLER2_T_MODE_DDR4 0x0050
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_CTRLLER_DATA_SCRAMBLE_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_CTRLLER_DATA_SCRAMBLE_DDR4 0x0051
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_CTRLLER_ON_DIMM_TEMP_SENSOR_EN_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_CTRLLER_ON_DIMM_TEMP_SENSOR_EN_DDR4 0x0052
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_CTRLLER_CMD_THROTTLE_MODE_CTL_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_CTRLLER_CMD_THROTTLE_MODE_CTL_DDR4 0x0053
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_CTRLLER_CMD_THROTTLE_MODE_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_CTRLLER_CMD_THROTTLE_MODE_DDR4 0x0054
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_CTRLLER_WR_CRC_EN_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_CTRLLER_WR_CRC_EN_DDR4 0x0055
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_GEAR_DOWN_MODE_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_GEAR_DOWN_MODE_DDR4 0x0056
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_HW_HISTORY_MECH_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_HW_HISTORY_MECH_DDR4 0x0057
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_DRAM_PARITY_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_DRAM_PARITY_DDR4 0x0058
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_RCD_PARITY_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_RCD_PARITY_DDR4 0x0059
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_DBI_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_DBI_DDR4 0x005A
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_ADDR_TWEAK_EN_CTRL_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_ADDR_TWEAK_EN_CTRL_DDR4 0x005B
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_ADDR_TWEAK_EN_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_ADDR_TWEAK_EN_DDR4 0x005C
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_DATA_ENCRYPTION_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_DATA_ENCRYPTION_DDR4 0x005D
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_FORCE_ENCRYPTION_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_FORCE_ENCRYPTION_DDR4 0x005E
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_FINE_GRAN_REF_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_FINE_GRAN_REF_DDR4 0x005F
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_CTRLLER_PWR_DN_EN_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_CTRLLER_PWR_DN_EN_DDR4 0x0060
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_CTRLLER_PWR_DN_MO_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_CTRLLER_PWR_DN_MO_DDR4 0x0061
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_CTRLLER_PD_DLY_CTL_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_CTRLLER_PD_DLY_CTL_DDR4 0x0062
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_CTRLLER_PD_DLY_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_CTRLLER_PD_DLY_DDR4 0x0063
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_CTRLLER_AGGRESSIVE_PWR_DOWN_EN_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_CTRLLER_AGGRESSIVE_PWR_DOWN_EN_DDR4 0x0064
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_CTRLLER_AGGRE_PD_DLY_CTL_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_CTRLLER_AGGRE_PD_DLY_CTL_DDR4 0x0065
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_CTRLLER_AGGRE_PD_DLY_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_CTRLLER_AGGRE_PD_DLY_DDR4 0x0066
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_CTRLLER_PHY_POWER_SAVING_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_CTRLLER_PHY_POWER_SAVING_DDR4 0x0067
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_CTRLLER_PD_PHY_POWER_SAVE_DIS_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_CTRLLER_PD_PHY_POWER_SAVE_DIS_DDR4 0x0068
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_CTRLLER_PHY_RECEIVER_POWER_MODE_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_CTRLLER_PHY_RECEIVER_POWER_MODE_DDR4 0x0069
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_CTRLLER_MEM_PWR_POLICY_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_CTRLLER_MEM_PWR_POLICY_DDR4 0x006A
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_CTRLLER_ALL_MEM_CLKS_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_CTRLLER_ALL_MEM_CLKS_DDR4 0x006B
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_CTRLLER_ALL_CKE_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_CTRLLER_ALL_CKE_DDR4 0x006C
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_CTRLLER_ALL_CS_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_CTRLLER_ALL_CS_DDR4 0x006D
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_DATA_POISONING_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_DATA_POISONING_DDR4 0x006E
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_ADDR_CMD_PARITY_RETRY_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_ADDR_CMD_PARITY_RETRY_DDR4 0x006F
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_ADDR_CMD_PARITY_ERROR_MAX_REPLAY_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_ADDR_CMD_PARITY_ERROR_MAX_REPLAY_DDR4 0x0070
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_WRITE_CRC_RETRY_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_WRITE_CRC_RETRY_DDR4 0x0071
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_WRITE_CRC_ERROR_MAX_REPLAY_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_WRITE_CRC_ERROR_MAX_REPLAY_DDR4 0x0072
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_INJECT_TX_CMD_PARITY_ERRORS_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_INJECT_TX_CMD_PARITY_ERRORS_DDR4 0x0073
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_CTRLLER_DRAM_ECC_SYMBOL_SIZE_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_CTRLLER_DRAM_ECC_SYMBOL_SIZE_DDR4 0x0074
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_CTRLLER_DRAM_ECC_EN_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_CTRLLER_DRAM_ECC_EN_DDR4 0x0075
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_DATA_BUS_CONFIG_CTL_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_DATA_BUS_CONFIG_CTL_DDR4 0x0076
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_CTRLLER_DATA_DRV_STR_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_CTRLLER_DATA_DRV_STR_DDR4 0x0077
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_CTRLLER_RTT_NOM_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_CTRLLER_RTT_NOM_DDR4 0x0078
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_CTRLLER_RTT_WR_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_CTRLLER_RTT_WR_DDR4 0x0079
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_CTRLLER_RTT_PARK_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_CTRLLER_RTT_PARK_DDR4 0x007A
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_TIMING_A_RD_PTR_MP0_CTL_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_TIMING_A_RD_PTR_MP0_CTL_DDR4 0x007B
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_TIMING_A_RD_PTR_MP0_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_TIMING_A_RD_PTR_MP0_DDR4 0x007C
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_TIMING_A_RD_PTR_MP1_CTL_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_TIMING_A_RD_PTR_MP1_CTL_DDR4 0x007D
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_TIMING_A_RD_PTR_MP1_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_TIMING_A_RD_PTR_MP1_DDR4 0x007E
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_DFI_MRL_MARGIN_CTL_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_DFI_MRL_MARGIN_CTL_DDR4 0x007F
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_DFI_MRL_MARGIN_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_DFI_MRL_MARGIN_DDR4 0x0080
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_PER_RANK_TIMING_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_PER_RANK_TIMING_DDR4 0x0081
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_CTRLLER_PMU_TRAIN_MODE_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_CTRLLER_PMU_TRAIN_MODE_DDR4 0x0082
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_CTRLLER_MR6_VREF_DQ_CTRL_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_CTRLLER_MR6_VREF_DQ_CTRL_DDR4 0x0083
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_CTRLLER_MR6_VREF_DQ_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_CTRLLER_MR6_VREF_DQ_DDR4 0x0084
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_VREF_RANGE_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_VREF_RANGE_DDR4 0x0085
#endif

#ifndef APCB_TOKEN_CBS_DBG_CLDO_E12_GA
  #define APCB_TOKEN_CBS_DBG_CLDO_E12_GA 0x0086
#endif

#ifndef APCB_TOKEN_CBS_DBG_CLDO_DDR
  #define APCB_TOKEN_CBS_DBG_CLDO_DDR 0x0087
#endif

#ifndef APCB_TOKEN_CBS_DBG_CLDO_WAFL
  #define APCB_TOKEN_CBS_DBG_CLDO_WAFL 0x0088
#endif

#ifndef APCB_TOKEN_CBS_DBG_CLDO_E12_GB
  #define APCB_TOKEN_CBS_DBG_CLDO_E12_GB 0x0089
#endif

#ifndef APCB_TOKEN_CBS_DBG_CLDO_VDDM0
  #define APCB_TOKEN_CBS_DBG_CLDO_VDDM0 0x008A
#endif

#ifndef APCB_TOKEN_CBS_DBG_CLDO_VDDM1
  #define APCB_TOKEN_CBS_DBG_CLDO_VDDM1 0x008B
#endif

#ifndef APCB_TOKEN_CBS_DBG_CLDO_VDDP_CTL
  #define APCB_TOKEN_CBS_DBG_CLDO_VDDP_CTL 0x008C
#endif

#ifndef APCB_TOKEN_CBS_DBG_CLDOVDD_PVOLTAGE
  #define APCB_TOKEN_CBS_DBG_CLDOVDD_PVOLTAGE 0x008D
#endif

#ifndef APCB_TOKEN_CBS_DBG_CLDO_VDDM_CTL
  #define APCB_TOKEN_CBS_DBG_CLDO_VDDM_CTL 0x008E
#endif

#ifndef APCB_TOKEN_CBS_DBG_CLDOVDD_MVOLTAGE
  #define APCB_TOKEN_CBS_DBG_CLDOVDD_MVOLTAGE 0x008F
#endif

#ifndef APCB_TOKEN_CBS_DBG_CPU_GEN_ABL_BP
  #define APCB_TOKEN_CBS_DBG_CPU_GEN_ABL_BP 0x0090
#endif

#ifndef APCB_TOKEN_CBS_DBG_CPU_GEN_ABL_CON_OUT
  #define APCB_TOKEN_CBS_DBG_CPU_GEN_ABL_CON_OUT 0x0091
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_UMC_KEY0_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_UMC_KEY0_DDR4 0x0092
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_CTRLLER_PMU_TRAIN_DFE_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_CTRLLER_PMU_TRAIN_DFE_DDR4 0x0093
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_CTRLLER_PMU_TRAIN_FFE_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_CTRLLER_PMU_TRAIN_FFE_DDR4 0x0094
#endif

#ifndef APCB_TOKEN_CBS_DBG_GNB_DBGU_NBIO_PORT80_TRACING
  #define APCB_TOKEN_CBS_DBG_GNB_DBGU_NBIO_PORT80_TRACING 0x0095
#endif

#ifndef APCB_TOKEN_CBS_DBG_GNB_DBGU_NBIO_PORT80_TIMESTAMP
  #define APCB_TOKEN_CBS_DBG_GNB_DBGU_NBIO_PORT80_TIMESTAMP 0x0096
#endif

#ifndef APCB_TOKEN_CBS_DBG_GNB_RESERVED1
  #define APCB_TOKEN_CBS_DBG_GNB_RESERVED1 0x0097
#endif

#ifndef APCB_TOKEN_CBS_DBG_GNB_RESERVED2
  #define APCB_TOKEN_CBS_DBG_GNB_RESERVED2 0x0098
#endif

#ifndef APCB_TOKEN_CBS_DF_DBG_CAKE_TKN_THRESH
  #define APCB_TOKEN_CBS_DF_DBG_CAKE_TKN_THRESH 0x0099
#endif

#ifndef APCB_TOKEN_CBS_DF_DBG_OPT_CAKE_DAT_LAT
  #define APCB_TOKEN_CBS_DF_DBG_OPT_CAKE_DAT_LAT 0x009A
#endif

#ifndef APCB_TOKEN_CBS_DF_DBG_CPU_MSTR_RCV_PRB_RSP
  #define APCB_TOKEN_CBS_DF_DBG_CPU_MSTR_RCV_PRB_RSP 0x009B
#endif

#ifndef APCB_TOKEN_CBS_DF_DBG_IO_MSTR_RCV_PRB_RSP
  #define APCB_TOKEN_CBS_DF_DBG_IO_MSTR_RCV_PRB_RSP 0x009C
#endif

#ifndef APCB_TOKEN_CBS_DBG_CLDO_VDDM
  #define APCB_TOKEN_CBS_DBG_CLDO_VDDM 0x009D
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_PSTATES_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_PSTATES_DDR4 0x009E
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_CTRLLER_POST_PACKAGE_REPAIR_EN_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_CTRLLER_POST_PACKAGE_REPAIR_EN_DDR4 0x009F
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_CTRLLER_POST_PACKAGE_REPAIR_ALL_BANKS_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_CTRLLER_POST_PACKAGE_REPAIR_ALL_BANKS_DDR4 0x00A0
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_CTRLLER_POST_PACKAGE_REPAIR_ALL_RANKS_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_CTRLLER_POST_PACKAGE_REPAIR_ALL_RANKS_DDR4 0x00A1
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_TIMING_TRDRD_SC_L_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_TIMING_TRDRD_SC_L_DDR4 0x00A2
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_TIMING_TWRWR_SC_L_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_TIMING_TWRWR_SC_L_DDR4 0x00A3
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_TIMING_TCWL_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_TIMING_TCWL_DDR4 0x00A4
#endif

#ifndef APCB_TOKEN_CBS_DBG_CPU_GEN_ABL_HDT_OUT
  #define APCB_TOKEN_CBS_DBG_CPU_GEN_ABL_HDT_OUT 0x00A5
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_CTRLLER_PMU_DELAY_WEIGHT2_D_CTRL_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_CTRLLER_PMU_DELAY_WEIGHT2_D_CTRL_DDR4 0x00A6
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_CTRLLER_PMU_DELAY_WEIGHT2_D_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_CTRLLER_PMU_DELAY_WEIGHT2_D_DDR4 0x00A7
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_CTRLLER_PMU_VOLTAGE_WEIGHT2_D_CTRL_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_CTRLLER_PMU_VOLTAGE_WEIGHT2_D_CTRL_DDR4 0x00A8
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_CTRLLER_PMU_VOLTAGE_WEIGHT2_D_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_CTRLLER_PMU_VOLTAGE_WEIGHT2_D_DDR4 0x00A9
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_CTRLLER_PMU_BITS_PER_POINT_CTRL_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_CTRLLER_PMU_BITS_PER_POINT_CTRL_DDR4 0x00AA
#endif

#ifndef APCB_TOKEN_CBS_DBG_MEM_CTRLLER_PMU_BITS_PER_POINT_DDR4
  #define APCB_TOKEN_CBS_DBG_MEM_CTRLLER_PMU_BITS_PER_POINT_DDR4 0x00AB
#endif

#ifndef APCB_TOKEN_CBS_DBG_CPU_PM_SC_THROTTLE
  #define APCB_TOKEN_CBS_DBG_CPU_PM_SC_THROTTLE 0x00AC
#endif

#ifndef APCB_TOKEN_CBS_DBG_CPU_PM_SC_THROTTLE_CTRL
  #define APCB_TOKEN_CBS_DBG_CPU_PM_SC_THROTTLE_CTRL 0x00AD
#endif

#ifndef APCB_TOKEN_CBS_DBG_CPU_GEN_ABL_HDT_OUT_DIE_CTRL
  #define APCB_TOKEN_CBS_DBG_CPU_GEN_ABL_HDT_OUT_DIE_CTRL 0x00AE
#endif

#ifndef APCB_TOKEN_CBS_DBG_CPU_GEN_ABL_HDT_OUT_DIE_BIT_MASK
  #define APCB_TOKEN_CBS_DBG_CPU_GEN_ABL_HDT_OUT_DIE_BIT_MASK 0x00AF
#endif

#ifndef APCB_TOKEN_CBS_DBG_END
  #define APCB_TOKEN_CBS_DBG_END 0x00B0
#endif

#ifndef APCB_TOKEN_CBS_DBG_LIMIT
  #define APCB_TOKEN_CBS_DBG_LIMIT 0x1FFF
#endif


//
// APCB Token Value Definition
//
#define APCB_TOKEN_CBS_CMN_CPU_SEV_ASID_SPACE_LIMIT_VALUE 5
#define APCB_TOKEN_CBS_CMN_MEM_TIMING_TRC_DDR4_VALUE 0x39
#define APCB_TOKEN_CBS_CMN_MEM_TIMING_TFAW_DDR4_VALUE 26
#define APCB_TOKEN_CBS_CMN_MEM_TIMING_TWR_DDR4_VALUE 18
#define APCB_TOKEN_CBS_CMN_MEM_TIMING_TRCPAGE_DDR4_VALUE 0
#define APCB_TOKEN_CBS_CMN_MEM_TIMING_TRDRD_SC_L_DDR4_VALUE 3
#define APCB_TOKEN_CBS_CMN_MEM_TIMING_TWRWR_SC_L_DDR4_VALUE 0x3
#define APCB_TOKEN_CBS_CMN_MEM_TIMING_TRFC_DDR4_VALUE 0x138
#define APCB_TOKEN_CBS_CMN_MEM_TIMING_TRFC2_DDR4_VALUE 0xC0
#define APCB_TOKEN_CBS_CMN_MEM_TIMING_TRFC4_DDR4_VALUE 0x84
#define APCB_TOKEN_CBS_CMN_MEM_MBIST_EN_VALUE 0
#define APCB_TOKEN_CBS_CMN_MEM_MBIST_SUB_TEST_VALUE 0
#define APCB_TOKEN_CBS_CMN_CLDOVDD_PVOLTAGE_VALUE 0
#define APCB_TOKEN_CBS_CMN_AVS_CONTROL_VALUE 0
#define APCB_TOKEN_CBS_CMN_BIOS_SPI_SPEED_MODE_VALUE 0xf

//
// Memory CMN Token Attributes Data
//
#define APCB_CBS_CMN_DEF_ATRIBS_AUTOGEN \
{APCB_TIME_POINT_ANY, APCB_TOKEN_CBS_CMN_CPU_SEV_ASID_SPACE_LIMIT, sizeof (UINT32) - 1, 0}, \
{APCB_TIME_POINT_ANY, APCB_TOKEN_CBS_CMN_MEM_TIMING_TRC_DDR4, sizeof (UINT8) - 1, 0}, \
{APCB_TIME_POINT_ANY, APCB_TOKEN_CBS_CMN_MEM_TIMING_TFAW_DDR4, sizeof (UINT8) - 1, 0}, \
{APCB_TIME_POINT_ANY, APCB_TOKEN_CBS_CMN_MEM_TIMING_TWR_DDR4, sizeof (UINT8) - 1, 0}, \
{APCB_TIME_POINT_ANY, APCB_TOKEN_CBS_CMN_MEM_TIMING_TRCPAGE_DDR4, sizeof (UINT16) - 1, 0}, \
{APCB_TIME_POINT_ANY, APCB_TOKEN_CBS_CMN_MEM_TIMING_TRDRD_SC_L_DDR4, sizeof (UINT8) - 1, 0}, \
{APCB_TIME_POINT_ANY, APCB_TOKEN_CBS_CMN_MEM_TIMING_TWRWR_SC_L_DDR4, sizeof (UINT8) - 1, 0}, \
{APCB_TIME_POINT_ANY, APCB_TOKEN_CBS_CMN_MEM_TIMING_TRFC_DDR4, sizeof (UINT16) - 1, 0}, \
{APCB_TIME_POINT_ANY, APCB_TOKEN_CBS_CMN_MEM_TIMING_TRFC2_DDR4, sizeof (UINT16) - 1, 0}, \
{APCB_TIME_POINT_ANY, APCB_TOKEN_CBS_CMN_MEM_TIMING_TRFC4_DDR4, sizeof (UINT16) - 1, 0}, \
{APCB_TIME_POINT_ANY, APCB_TOKEN_CBS_CMN_MEM_MBIST_EN, sizeof (UINT8) - 1, 0}, \
{APCB_TIME_POINT_ANY, APCB_TOKEN_CBS_CMN_MEM_MBIST_SUB_TEST, sizeof (UINT8) - 1, 0}, \
{APCB_TIME_POINT_ANY, APCB_TOKEN_CBS_CMN_CLDOVDD_PVOLTAGE, sizeof (UINT32) - 1, 0}, \
{APCB_TIME_POINT_ANY, APCB_TOKEN_CBS_CMN_AVS_CTRL, sizeof (UINT8) - 1, 0}, \
{APCB_TIME_POINT_ANY, APCB_TOKEN_CBS_CMN_BIOS_SPI_SPEED_MODE, sizeof (UINT8) - 1, 0}, \

//
// Memory CMN Value
//
#define APCB_CBS_CMN_DEF_VALUES_AUTOGEN \
  BSU32 (APCB_TOKEN_CBS_CMN_CPU_SEV_ASID_SPACE_LIMIT_VALUE), \
  BSU08 (APCB_TOKEN_CBS_CMN_MEM_TIMING_TRC_DDR4_VALUE), \
  BSU08 (APCB_TOKEN_CBS_CMN_MEM_TIMING_TFAW_DDR4_VALUE), \
  BSU08 (APCB_TOKEN_CBS_CMN_MEM_TIMING_TWR_DDR4_VALUE), \
  BSU16 (APCB_TOKEN_CBS_CMN_MEM_TIMING_TRCPAGE_DDR4_VALUE), \
  BSU08 (APCB_TOKEN_CBS_CMN_MEM_TIMING_TRDRD_SC_L_DDR4_VALUE), \
  BSU08 (APCB_TOKEN_CBS_CMN_MEM_TIMING_TWRWR_SC_L_DDR4_VALUE), \
  BSU16 (APCB_TOKEN_CBS_CMN_MEM_TIMING_TRFC_DDR4_VALUE), \
  BSU16 (APCB_TOKEN_CBS_CMN_MEM_TIMING_TRFC2_DDR4_VALUE), \
  BSU16 (APCB_TOKEN_CBS_CMN_MEM_TIMING_TRFC4_DDR4_VALUE), \
  BSU08 (APCB_TOKEN_CBS_CMN_MEM_MBIST_EN_VALUE), \
  BSU08 (APCB_TOKEN_CBS_CMN_MEM_MBIST_SUB_TEST_VALUE), \
  BSU32 (APCB_TOKEN_CBS_CMN_CLDOVDD_PVOLTAGE_VALUE), \
  BSU08 (APCB_TOKEN_CBS_CMN_AVS_CONTROL_VALUE), \
  BSU08 (APCB_TOKEN_CBS_CMN_BIOS_SPI_SPEED_MODE_VALUE), \

//
// Memory DBG Token Attributes Data
//
#define APCB_CBS_DBG_DEF_ATRIBS_AUTOGEN

//
// Memory DBG Value
//
#define APCB_CBS_DBG_DEF_VALUE_AUTOGEN

#endif //_APCB_AUTOGEN_ZP_H_
