/* $NoKeywords:$ */
/**
 * @file
 *
 * APCB DXE Driver
 *
 *
 * @xrefitem bom "File Content Label" "Release Content"
 * @e project:      AGESA
 * @e sub-project:  APCB
 * @e \$Revision$   @e \$Date$
 *
 */
/*****************************************************************************
 *
 * 
 * Copyright 2016 - 2019 CHENGDU HAIGUANG IC DESIGN CO., LTD. All Rights Reserved.
 * 
 * HYGON is granting you permission to use this software (the Materials)
 * pursuant to the terms and conditions of your Software License Agreement
 * with HYGON.  This header does *NOT* give you permission to use the Materials
 * or any rights under HYGON's intellectual property.  Your use of any portion
 * of these Materials shall constitute your acceptance of those terms and
 * conditions.  If you do not agree to the terms and conditions of the Software
 * License Agreement, please do not use any portion of these Materials.
 * 
 * CONFIDENTIALITY:  The Materials and all other information, identified as
 * confidential and provided to you by HYGON shall be kept confidential in
 * accordance with the terms and conditions of the Software License Agreement.
 * 
 * LIMITATION OF LIABILITY: THE MATERIALS AND ANY OTHER RELATED INFORMATION
 * PROVIDED TO YOU BY HYGON ARE PROVIDED "AS IS" WITHOUT ANY EXPRESS OR IMPLIED
 * WARRANTY OF ANY KIND, INCLUDING BUT NOT LIMITED TO WARRANTIES OF
 * MERCHANTABILITY, NONINFRINGEMENT, TITLE, FITNESS FOR ANY PARTICULAR PURPOSE,
 * OR WARRANTIES ARISING FROM CONDUCT, COURSE OF DEALING, OR USAGE OF TRADE.
 * IN NO EVENT SHALL HYGON OR ITS LICENSORS BE LIABLE FOR ANY DAMAGES WHATSOEVER
 * (INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOSS OF PROFITS, BUSINESS
 * INTERRUPTION, OR LOSS OF INFORMATION) ARISING OUT OF HYGON'S NEGLIGENCE,
 * GROSS NEGLIGENCE, THE USE OF OR INABILITY TO USE THE MATERIALS OR ANY OTHER
 * RELATED INFORMATION PROVIDED TO YOU BY HYGON, EVEN IF HYGON HAS BEEN ADVISED OF
 * THE POSSIBILITY OF SUCH DAMAGES.  BECAUSE SOME JURISDICTIONS PROHIBIT THE
 * EXCLUSION OR LIMITATION OF LIABILITY FOR CONSEQUENTIAL OR INCIDENTAL DAMAGES,
 * THE ABOVE LIMITATION MAY NOT APPLY TO YOU.
 * 
 * HYGON does not assume any responsibility for any errors which may appear in
 * the Materials or any other related information provided to you by HYGON, or
 * result from use of the Materials or any related information.
 * 
 * You agree that you will not reverse engineer or decompile the Materials.
 * 
 * NO SUPPORT OBLIGATION: HYGON is not obligated to furnish, support, or make any
 * further information, software, technical information, know-how, or show-how
 * available to you.  Additionally, HYGON retains the right to modify the
 * Materials at any time, without notice, and is not obligated to provide such
 * modified Materials to you.
 * 
 * AMD GRANT HYGON DECLARATION: ADVANCED MICRO DEVICES, INC.(AMD) granted HYGON has
 * the right to redistribute HYGON's Agesa version to BIOS Vendors and HYGON has
 * the right to make the modified version available for use with HYGON's PRODUCT.
 ******************************************************************************
 */
#include "AGESA.h"
#include "Firmwares/ZP/APCB.h"
#include "ApcbCommon.h"
#include <Library/IdsLib.h>
#include <Filecode.h>

#define FILECODE PSP_APCB_TOKENS_CBS_EXT_TOKENS_FILECODE                  

//
// APCB CBS Token ID definitions
//
TOKEN_PAIR CbsExtTokenPair[] = {
  { APCB_ID_CBS_DF_CMN_GMI_ENCRYPTION,                APCB_TOKEN_CBS_DF_CMN_GMI_ENCRYPTION               },
  { APCB_ID_CBS_DF_CMN_X_GMI_ENCRYPTION,              APCB_TOKEN_CBS_DF_CMN_X_GMI_ENCRYPTION             },
  { APCB_ID_CBS_DF_CMN_CC6_MEM_ENCRYPTION,            APCB_TOKEN_CBS_DF_CMN_CC6_MEM_ENCRYPTION           },
  { APCB_ID_CBS_DF_CMN_CC6_ALLOCATION_SCHEME,         APCB_TOKEN_CBS_DF_CMN_CC6_ALLOCATION_SCHEME        },
  { APCB_ID_CBS_DF_CMN_SYS_PROBE_FILTER,              APCB_TOKEN_CBS_DF_CMN_SYS_PROBE_FILTER             },
  { APCB_ID_CBS_DF_CMN_MEM_INTLV,                     APCB_TOKEN_CBS_DF_CMN_MEM_INTLV                    },
  { APCB_ID_CBS_DF_CMN_MEM_INTLV_SIZE,                APCB_TOKEN_CBS_DF_CMN_MEM_INTLV_SIZE               },
  { APCB_ID_CBS_DF_CMN_CHNL_INTLV_HASH,               APCB_TOKEN_CBS_DF_CMN_CHNL_INTLV_HASH              },
  { APCB_ID_CBS_CMN_MEM_MAPPING_BANK_INTERLEAVE_DDR4, APCB_TOKEN_CBS_CMN_MEM_MAPPING_BANK_INTERLEAVE_DDR4},
  { APCB_ID_CBS_CMN_MEM_CTRLLER_BANK_GROUP_SWAP_DDR4, APCB_TOKEN_CBS_CMN_MEM_CTRLLER_BANK_GROUP_SWAP_DDR4},
  { APCB_ID_CBS_CMN_MEM_CTRLLER_BANK_SWIZZLE_DDR4,    APCB_TOKEN_CBS_CMN_MEM_CTRLLER_BANK_SWIZZLE_DDR4   },
  { APCB_ID_CBS_CMN_MEM_ADDRESS_HASHING_DDR4,         APCB_TOKEN_CBS_CMN_MEM_ADDRESS_HASHING_DDR4        },
  { APCB_ID_CBS_CMN_MEM_SPEED_DDR4,                   APCB_TOKEN_CBS_CMN_MEM_SPEED_DDR4                  },
  { APCB_ID_CBS_CMN_MEM_TIMING_TCL_DDR4,              APCB_TOKEN_CBS_CMN_MEM_TIMING_TCL_DDR4             },
  { APCB_ID_CBS_CMN_MEM_TIMING_TRCDRD_DDR4,           APCB_TOKEN_CBS_CMN_MEM_TIMING_TRCDRD_DDR4          },
  { APCB_ID_CBS_CMN_MEM_TIMING_TRCDWR_DDR4,           APCB_TOKEN_CBS_CMN_MEM_TIMING_TRCDWR_DDR4          },
  { APCB_ID_CBS_CMN_MEM_TIMING_TRP_DDR4,              APCB_TOKEN_CBS_CMN_MEM_TIMING_TRP_DDR4             },
  { APCB_ID_CBS_CMN_MEM_TIMING_TRAS_DDR4,             APCB_TOKEN_CBS_CMN_MEM_TIMING_TRAS_DDR4            },
  { APCB_ID_CBS_CMN_MEM_DATA_POISONING_DDR4,          APCB_TOKEN_CBS_CMN_MEM_DATA_POISONING_DDR4         },
  { APCB_ID_CBS_CMN_MEM_ADDRESS_HASH_BANK_DDR4,       APCB_TOKEN_CBS_CMN_MEM_ADDRESS_HASH_BANK_DDR4      },
  { APCB_ID_CBS_CMN_MEM_ADDRESS_HASH_CS_DDR4,         APCB_TOKEN_CBS_CMN_MEM_ADDRESS_HASH_CS_DDR4        },
  { APCB_ID_CBS_CMN_MEM_TSME_DDR4,                    APCB_TOKEN_CBS_CMN_MEM_TSME_DDR4                   },
  { APCB_ID_CBS_CMN_MEM_OVERCLOCK_DDR4,               APCB_TOKEN_CBS_CMN_MEM_OVERCLOCK_DDR4              },
  { APCB_ID_CBS_CMN_GNB_GFX_UMA_MODE,                 APCB_TOKEN_CBS_CMN_GNB_GFX_UMA_MODE                },
  { APCB_ID_CBS_CMN_GNB_GFX_UMA_VERSION,              APCB_TOKEN_CBS_CMN_GNB_GFX_UMA_VERSION             },
  { APCB_ID_CBS_CMN_GNB_GFX_DISPLAY_RESOLUTION,       APCB_TOKEN_CBS_CMN_GNB_GFX_DISPLAY_RESOLUTION      },
  { APCB_ID_CBS_CMN_GNB_GFX_UMA_FRAME_BUFFER_SIZE,    APCB_TOKEN_CBS_CMN_GNB_GFX_UMA_FRAME_BUFFER_SIZE   },
  { APCB_ID_CBS_CMN_CPU_SEV_ASID_SPACE_LIMIT,         APCB_TOKEN_CBS_CMN_CPU_SEV_ASID_SPACE_LIMIT        },
  { APCB_ID_CBS_CMN_MEM_SPD_READ_OPTIMIZATION_DDR4,   APCB_TOKEN_CBS_CMN_MEM_SPD_READ_OPTIMIZATION_DDR4  },
  { APCB_ID_CBS_CMN_MEM_MBIST_EN,                     APCB_TOKEN_CBS_CMN_MEM_MBIST_EN                    },
  { APCB_ID_CBS_CMN_MEM_MBIST_TESTMODE,               APCB_TOKEN_CBS_CMN_MEM_MBIST_TESTMODE              },
  { APCB_ID_CBS_DF_CMN_MEM_CLEAR,                     APCB_TOKEN_CBS_DF_CMN_MEM_CLEAR                    },
  { APCB_ID_CBS_CMN_MEM_TIMING_TRC_CTRL_DDR4,         APCB_TOKEN_CBS_CMN_MEM_TIMING_TRC_CTRL_DDR4        },
  { APCB_ID_CBS_CMN_MEM_TIMING_TRC_DDR4,              APCB_TOKEN_CBS_CMN_MEM_TIMING_TRC_DDR4             },
  { APCB_ID_CBS_CMN_MEM_TIMING_TRRD_S_DDR4,           APCB_TOKEN_CBS_CMN_MEM_TIMING_TRRD_S_DDR4          },
  { APCB_ID_CBS_CMN_MEM_TIMING_TRRD_L_DDR4,           APCB_TOKEN_CBS_CMN_MEM_TIMING_TRRD_L_DDR4          },
  { APCB_ID_CBS_CMN_MEM_TIMING_TFAW_CTRL_DDR4,        APCB_TOKEN_CBS_CMN_MEM_TIMING_TFAW_CTRL_DDR4       },
  { APCB_ID_CBS_CMN_MEM_TIMING_TFAW_DDR4,             APCB_TOKEN_CBS_CMN_MEM_TIMING_TFAW_DDR4            },
  { APCB_ID_CBS_CMN_MEM_TIMING_TWTR_S_DDR4,           APCB_TOKEN_CBS_CMN_MEM_TIMING_TWTR_S_DDR4          },
  { APCB_ID_CBS_CMN_MEM_TIMING_TWTR_L_DDR4,           APCB_TOKEN_CBS_CMN_MEM_TIMING_TWTR_L_DDR4          },
  { APCB_ID_CBS_CMN_MEM_TIMING_TWR_CTRL_DDR4,         APCB_TOKEN_CBS_CMN_MEM_TIMING_TWR_CTRL_DDR4        },
  { APCB_ID_CBS_CMN_MEM_TIMING_TWR_DDR4,              APCB_TOKEN_CBS_CMN_MEM_TIMING_TWR_DDR4             },
  { APCB_ID_CBS_CMN_MEM_TIMING_TRCPAGE_CTRL_DDR4,     APCB_TOKEN_CBS_CMN_MEM_TIMING_TRCPAGE_CTRL_DDR4    },
  { APCB_ID_CBS_CMN_MEM_TIMING_TRCPAGE_DDR4,          APCB_TOKEN_CBS_CMN_MEM_TIMING_TRCPAGE_DDR4         },
  { APCB_ID_CBS_CMN_MEM_TIMING_TRDRD_SC_L_CTRL_DDR4,  APCB_TOKEN_CBS_CMN_MEM_TIMING_TRDRD_SC_L_CTRL_DDR4 },
  { APCB_ID_CBS_CMN_MEM_TIMING_TRDRD_SC_L_DDR4,       APCB_TOKEN_CBS_CMN_MEM_TIMING_TRDRD_SC_L_DDR4      },
  { APCB_ID_CBS_CMN_MEM_TIMING_TWRWR_SC_L_CTRL_DDR4,  APCB_TOKEN_CBS_CMN_MEM_TIMING_TWRWR_SC_L_CTRL_DDR4 },
  { APCB_ID_CBS_CMN_MEM_TIMING_TWRWR_SC_L_DDR4,       APCB_TOKEN_CBS_CMN_MEM_TIMING_TWRWR_SC_L_DDR4      },
  { APCB_ID_CBS_CMN_MEM_TIMING_TRFC_CTRL_DDR4,        APCB_TOKEN_CBS_CMN_MEM_TIMING_TRFC_CTRL_DDR4       },
  { APCB_ID_CBS_CMN_MEM_TIMING_TRFC_DDR4,             APCB_TOKEN_CBS_CMN_MEM_TIMING_TRFC_DDR4            },
  { APCB_ID_CBS_CMN_MEM_TIMING_TRFC2_CTRL_DDR4,       APCB_TOKEN_CBS_CMN_MEM_TIMING_TRFC2_CTRL_DDR4      },
  { APCB_ID_CBS_CMN_MEM_TIMING_TRFC2_DDR4,            APCB_TOKEN_CBS_CMN_MEM_TIMING_TRFC2_DDR4           },
  { APCB_ID_CBS_CMN_MEM_TIMING_TRFC4_CTRL_DDR4,       APCB_TOKEN_CBS_CMN_MEM_TIMING_TRFC4_CTRL_DDR4      },
  { APCB_ID_CBS_CMN_MEM_TIMING_TRFC4_DDR4,            APCB_TOKEN_CBS_CMN_MEM_TIMING_TRFC4_DDR4           },
  { APCB_ID_CBS_CMN_MEM_OVERCLOCK_FAIL_CNT,           APCB_TOKEN_CBS_CMN_MEM_OVERCLOCK_FAIL_CNT          },
  { APCB_ID_CBS_CMN_MEM_CTRLLER_PROC_ODT_DDR4,        APCB_TOKEN_CBS_CMN_MEM_CTRLLER_PROC_ODT_DDR4       },
  { APCB_ID_CBS_CMN_MEM_TIMING_TRDRD_SC_DDR4,         APCB_TOKEN_CBS_CMN_MEM_TIMING_TRDRD_SC_DDR4        },
  { APCB_ID_CBS_CMN_MEM_TIMING_TRDRD_SD_DDR4,         APCB_TOKEN_CBS_CMN_MEM_TIMING_TRDRD_SD_DDR4        },
  { APCB_ID_CBS_CMN_MEM_TIMING_TRDRD_DD_DDR4,         APCB_TOKEN_CBS_CMN_MEM_TIMING_TRDRD_DD_DDR4        },
  { APCB_ID_CBS_CMN_MEM_TIMING_TWRWR_SC_DDR4,         APCB_TOKEN_CBS_CMN_MEM_TIMING_TWRWR_SC_DDR4        },
  { APCB_ID_CBS_CMN_MEM_TIMING_TWRWR_SD_DDR4,         APCB_TOKEN_CBS_CMN_MEM_TIMING_TWRWR_SD_DDR4        },
  { APCB_ID_CBS_CMN_MEM_TIMING_TWRWR_DD_DDR4,         APCB_TOKEN_CBS_CMN_MEM_TIMING_TWRWR_DD_DDR4        },
  { APCB_ID_CBS_CMN_MEM_TIMING_TRDWR_DDR4,            APCB_TOKEN_CBS_CMN_MEM_TIMING_TRDWR_DDR4           },
  { APCB_ID_CBS_CMN_MEM_TIMING_TWRRD_DDR4,            APCB_TOKEN_CBS_CMN_MEM_TIMING_TWRRD_DDR4           },
  { APCB_ID_CBS_CMN_MEM_TIMING_TRTP_DDR4,             APCB_TOKEN_CBS_CMN_MEM_TIMING_TRTP_DDR4            },
  { APCB_ID_CBS_CMN_MEM_TIMING_TCWL_DDR4,             APCB_TOKEN_CBS_CMN_MEM_TIMING_TCWL_DDR4            },
  { APCB_ID_CBS_CMN_MEM_DATA_BUS_CONFIG_CTL_DDR4,     APCB_TOKEN_CBS_CMN_MEM_DATA_BUS_CONFIG_CTL_DDR4    },
  { APCB_ID_CBS_CMN_MEM_CTRLLER_RTT_NOM_DDR4,         APCB_TOKEN_CBS_CMN_MEM_CTRLLER_RTT_NOM_DDR4        },
  { APCB_ID_CBS_CMN_MEM_CTRLLER_RTT_WR_DDR4,          APCB_TOKEN_CBS_CMN_MEM_CTRLLER_RTT_WR_DDR4         },
  { APCB_ID_CBS_CMN_MEM_CTRLLER_RTT_PARK_DDR4,        APCB_TOKEN_CBS_CMN_MEM_CTRLLER_RTT_PARK_DDR4       },
  { APCB_ID_CBS_CMN_MEM_TIMING_TCKE_DDR4,             APCB_TOKEN_CBS_CMN_MEM_TIMING_TCKE_DDR4            },
  { APCB_ID_CBS_CMN_MEM_CTRLLER_DATA_SCRAMBLE_DDR4,   APCB_TOKEN_CBS_CMN_MEM_CTRLLER_DATA_SCRAMBLE_DDR4  },
};

UINT16
mTranslateCbsExtTokenId (
  IN       UINT16             CommonId
  )
{
  UINT16 i;

  for (i = 0; i < sizeof (CbsExtTokenPair) / sizeof (TOKEN_PAIR); i++) {
    if (CommonId == CbsExtTokenPair[i].ApcbCommonId) {
      return CbsExtTokenPair[i].ApcbToken;
    }
  }

  ASSERT (FALSE);

  return 0xFFFF;
}
