rem C:\PROGRA~1\TRENDP~1\PCSCAN.EXE C:\ C:\WINDOWS\COMMAND\ /NS /WIN95
REM [Header]
ECHO ON
                              
PATH E:\Tool\MASM611\BIN;
rem PATH C:\WINDOWS;C:\WINDOWS\COMMAND;D:\MASM611\BIN;D:\MASM611\BINR;D:\nc;D:\flash\tko;d:\tools;d:\flash\exe
rem set TEMP=C:\TEMP
rem SET PATH=C:\WIN95;C:\WIN95\COMMAND;C:\MASM611\BIN;C:\MASM611\BINR;c:\vss\win32;%PATH%
SET LIB=E:\Tool\MASM611\LIB
SET INCLUDE=E:\Tool\MASM611\INCLUDE
SET INIT=E:\Tool\MASM611\INIT
rem SET HELPFILES=C:\MASM611\HELP\*.HLP
SET TMP=E:\Tool\MASM611\TMP
rem SET BOXER=e.bkp c h m t8 w255 T kr10 b l 

REM [CD-ROM Drive]

REM [Miscellaneous]

REM [Display]

REM [Sound, MIDI, or Video Capture Card]

REM [Mouse]

