////////////////////////////////////////////////////////////////////////////////
/// ADVANCED MICRO DEVICES, INC.
/// This an auto generated file. Do not modify.
////////////////////////////////////////////////////////////////////////////////

SL1R2_MAKE_TX_EQ_FREQ_TABLE_COMPACT(XGMI_TX_EQ_SPEED_107, SOC_GEN_1, SOC_SL1R2,
    MAKE_TX_EQ_LIST_COMPACT(MAKE_TX_EQ_SOCKET0_DIE0_EACH_LANES_COMPACT(),
        MAKE_TX_EQ_LANE_DATA( 39, 4, 0 ),
        MAKE_TX_EQ_LANE_DATA( 37, 4, 8 ),
        MAKE_TX_EQ_LANE_DATA( 39, 0, 4 ),
        MAKE_TX_EQ_LANE_DATA( 36, 8, 8 ),
        MAKE_TX_EQ_LANE_DATA( 40, 0, 0 ),
        MAKE_TX_EQ_LANE_DATA( 40, 0, 0 ),
        MAKE_TX_EQ_LANE_DATA( 37, 4, 8 ),
        MAKE_TX_EQ_LANE_DATA( 38, 0, 8 ),
        MAKE_TX_EQ_LANE_DATA( 39, 0, 4 ),
        MAKE_TX_EQ_LANE_DATA( 39, 0, 4 ),
        MAKE_TX_EQ_LANE_DATA( 40, 0, 0 ),
        MAKE_TX_EQ_LANE_DATA( 40, 0, 0 ),
        MAKE_TX_EQ_LANE_DATA( 39, 0, 4 ),
        MAKE_TX_EQ_LANE_DATA( 40, 0, 0 ),
        MAKE_TX_EQ_LANE_DATA( 40, 0, 0 ),
        MAKE_TX_EQ_LANE_DATA( 40, 0, 0 )
    ),
    MAKE_TX_EQ_LIST_COMPACT(MAKE_TX_EQ_SOCKET0_DIE1_EACH_LANES_COMPACT(),
        MAKE_TX_EQ_LANE_DATA( 25, 0, 8 ),
        MAKE_TX_EQ_LANE_DATA( 27, 0, 2 ),
        MAKE_TX_EQ_LANE_DATA( 27, 0, 2 ),
        MAKE_TX_EQ_LANE_DATA( 28, 0, 0 ),
        MAKE_TX_EQ_LANE_DATA( 28, 0, 0 ),
        MAKE_TX_EQ_LANE_DATA( 28, 0, 0 ),
        MAKE_TX_EQ_LANE_DATA( 25, 0, 8 ),
        MAKE_TX_EQ_LANE_DATA( 25, 5, 5 ),
        MAKE_TX_EQ_LANE_DATA( 26, 0, 5 ),
        MAKE_TX_EQ_LANE_DATA( 28, 0, 0 ),
        MAKE_TX_EQ_LANE_DATA( 27, 0, 2 ),
        MAKE_TX_EQ_LANE_DATA( 26, 0, 5 ),
        MAKE_TX_EQ_LANE_DATA( 25, 0, 8 ),
        MAKE_TX_EQ_LANE_DATA( 25, 2, 8 ),
        MAKE_TX_EQ_LANE_DATA( 26, 0, 5 ),
        MAKE_TX_EQ_LANE_DATA( 26, 0, 5 )
    ),
    MAKE_TX_EQ_LIST_COMPACT(MAKE_TX_EQ_SOCKET1_DIE0_EACH_LANES_COMPACT(),
        MAKE_TX_EQ_LANE_DATA( 40, 0, 0 ),
        MAKE_TX_EQ_LANE_DATA( 37, 8, 4 ),
        MAKE_TX_EQ_LANE_DATA( 40, 0, 0 ),
        MAKE_TX_EQ_LANE_DATA( 39, 0, 4 ),
        MAKE_TX_EQ_LANE_DATA( 39, 4, 0 ),
        MAKE_TX_EQ_LANE_DATA( 40, 0, 0 ),
        MAKE_TX_EQ_LANE_DATA( 38, 4, 4 ),
        MAKE_TX_EQ_LANE_DATA( 38, 8, 0 ),
        MAKE_TX_EQ_LANE_DATA( 39, 0, 4 ),
        MAKE_TX_EQ_LANE_DATA( 39, 0, 4 ),
        MAKE_TX_EQ_LANE_DATA( 37, 0, 12 ),
        MAKE_TX_EQ_LANE_DATA( 38, 0, 8 ),
        MAKE_TX_EQ_LANE_DATA( 38, 8, 0 ),
        MAKE_TX_EQ_LANE_DATA( 38, 0, 8 ),
        MAKE_TX_EQ_LANE_DATA( 38, 4, 4 ),
        MAKE_TX_EQ_LANE_DATA( 40, 0, 0 )
    ),
    MAKE_TX_EQ_LIST_COMPACT(MAKE_TX_EQ_SOCKET1_DIE1_EACH_LANES_COMPACT(),
        MAKE_TX_EQ_LANE_DATA( 24, 5, 8 ),
        MAKE_TX_EQ_LANE_DATA( 28, 0, 0 ),
        MAKE_TX_EQ_LANE_DATA( 25, 8, 0 ),
        MAKE_TX_EQ_LANE_DATA( 25, 11, 0 ),
        MAKE_TX_EQ_LANE_DATA( 25, 5, 2 ),
        MAKE_TX_EQ_LANE_DATA( 26, 5, 0 ),
        MAKE_TX_EQ_LANE_DATA( 23, 11, 8 ),
        MAKE_TX_EQ_LANE_DATA( 26, 5, 0 ),
        MAKE_TX_EQ_LANE_DATA( 26, 5, 0 ),
        MAKE_TX_EQ_LANE_DATA( 25, 8, 2 ),
        MAKE_TX_EQ_LANE_DATA( 25, 8, 0 ),
        MAKE_TX_EQ_LANE_DATA( 27, 2, 0 ),
        MAKE_TX_EQ_LANE_DATA( 27, 2, 0 ),
        MAKE_TX_EQ_LANE_DATA( 25, 5, 5 ),
        MAKE_TX_EQ_LANE_DATA( 26, 5, 0 ),
        MAKE_TX_EQ_LANE_DATA( 26, 5, 0 )
    )
),

SL1R2_MAKE_TX_EQ_FREQ_TABLE_COMPACT(XGMI_TX_EQ_SPEED_107, SOC_GEN_2, SOC_SL1R2,
    MAKE_TX_EQ_LIST_COMPACT(MAKE_TX_EQ_SOCKET0_DIE0_EACH_LANES_COMPACT(),
        MAKE_TX_EQ_LANE_DATA( 39, 4, 0 ),
        MAKE_TX_EQ_LANE_DATA( 37, 4, 8 ),
        MAKE_TX_EQ_LANE_DATA( 39, 0, 4 ),
        MAKE_TX_EQ_LANE_DATA( 36, 8, 8 ),
        MAKE_TX_EQ_LANE_DATA( 40, 0, 0 ),
        MAKE_TX_EQ_LANE_DATA( 40, 0, 0 ),
        MAKE_TX_EQ_LANE_DATA( 37, 4, 8 ),
        MAKE_TX_EQ_LANE_DATA( 38, 0, 8 ),
        MAKE_TX_EQ_LANE_DATA( 39, 0, 4 ),
        MAKE_TX_EQ_LANE_DATA( 39, 0, 4 ),
        MAKE_TX_EQ_LANE_DATA( 40, 0, 0 ),
        MAKE_TX_EQ_LANE_DATA( 40, 0, 0 ),
        MAKE_TX_EQ_LANE_DATA( 39, 0, 4 ),
        MAKE_TX_EQ_LANE_DATA( 40, 0, 0 ),
        MAKE_TX_EQ_LANE_DATA( 40, 0, 0 ),
        MAKE_TX_EQ_LANE_DATA( 40, 0, 0 )
    ),
    MAKE_TX_EQ_LIST_COMPACT(MAKE_TX_EQ_SOCKET0_DIE1_EACH_LANES_COMPACT(),
        MAKE_TX_EQ_LANE_DATA( 25, 0, 8 ),
        MAKE_TX_EQ_LANE_DATA( 27, 0, 2 ),
        MAKE_TX_EQ_LANE_DATA( 27, 0, 2 ),
        MAKE_TX_EQ_LANE_DATA( 28, 0, 0 ),
        MAKE_TX_EQ_LANE_DATA( 28, 0, 0 ),
        MAKE_TX_EQ_LANE_DATA( 28, 0, 0 ),
        MAKE_TX_EQ_LANE_DATA( 25, 0, 8 ),
        MAKE_TX_EQ_LANE_DATA( 25, 5, 5 ),
        MAKE_TX_EQ_LANE_DATA( 26, 0, 5 ),
        MAKE_TX_EQ_LANE_DATA( 28, 0, 0 ),
        MAKE_TX_EQ_LANE_DATA( 27, 0, 2 ),
        MAKE_TX_EQ_LANE_DATA( 26, 0, 5 ),
        MAKE_TX_EQ_LANE_DATA( 25, 0, 8 ),
        MAKE_TX_EQ_LANE_DATA( 25, 2, 8 ),
        MAKE_TX_EQ_LANE_DATA( 26, 0, 5 ),
        MAKE_TX_EQ_LANE_DATA( 26, 0, 5 )
    ),
    MAKE_TX_EQ_LIST_COMPACT(MAKE_TX_EQ_SOCKET1_DIE0_EACH_LANES_COMPACT(),
        MAKE_TX_EQ_LANE_DATA( 40, 0, 0 ),
        MAKE_TX_EQ_LANE_DATA( 37, 8, 4 ),
        MAKE_TX_EQ_LANE_DATA( 40, 0, 0 ),
        MAKE_TX_EQ_LANE_DATA( 39, 0, 4 ),
        MAKE_TX_EQ_LANE_DATA( 39, 4, 0 ),
        MAKE_TX_EQ_LANE_DATA( 40, 0, 0 ),
        MAKE_TX_EQ_LANE_DATA( 38, 4, 4 ),
        MAKE_TX_EQ_LANE_DATA( 38, 8, 0 ),
        MAKE_TX_EQ_LANE_DATA( 39, 0, 4 ),
        MAKE_TX_EQ_LANE_DATA( 39, 0, 4 ),
        MAKE_TX_EQ_LANE_DATA( 37, 0, 12 ),
        MAKE_TX_EQ_LANE_DATA( 38, 0, 8 ),
        MAKE_TX_EQ_LANE_DATA( 38, 8, 0 ),
        MAKE_TX_EQ_LANE_DATA( 38, 0, 8 ),
        MAKE_TX_EQ_LANE_DATA( 38, 4, 4 ),
        MAKE_TX_EQ_LANE_DATA( 40, 0, 0 )
    ),
    MAKE_TX_EQ_LIST_COMPACT(MAKE_TX_EQ_SOCKET1_DIE1_EACH_LANES_COMPACT(),
        MAKE_TX_EQ_LANE_DATA( 24, 5, 8 ),
        MAKE_TX_EQ_LANE_DATA( 28, 0, 0 ),
        MAKE_TX_EQ_LANE_DATA( 25, 8, 0 ),
        MAKE_TX_EQ_LANE_DATA( 25, 11, 0 ),
        MAKE_TX_EQ_LANE_DATA( 25, 5, 2 ),
        MAKE_TX_EQ_LANE_DATA( 26, 5, 0 ),
        MAKE_TX_EQ_LANE_DATA( 23, 11, 8 ),
        MAKE_TX_EQ_LANE_DATA( 26, 5, 0 ),
        MAKE_TX_EQ_LANE_DATA( 26, 5, 0 ),
        MAKE_TX_EQ_LANE_DATA( 25, 8, 2 ),
        MAKE_TX_EQ_LANE_DATA( 25, 8, 0 ),
        MAKE_TX_EQ_LANE_DATA( 27, 2, 0 ),
        MAKE_TX_EQ_LANE_DATA( 27, 2, 0 ),
        MAKE_TX_EQ_LANE_DATA( 25, 5, 5 ),
        MAKE_TX_EQ_LANE_DATA( 26, 5, 0 ),
        MAKE_TX_EQ_LANE_DATA( 26, 5, 0 )
    )
),