////////////////////////////////////////////////////////////////////////////////
/// Copyright 2020 HYGON, INC. All Rights Reserved.
/// This file was generated by hgt xgmitxeqtune. Do not modify.
////////////////////////////////////////////////////////////////////////////////

SL1_MAKE_TX_EQ_FREQ_TABLE_COMPACT(XGMI_TX_EQ_SPEED_96, SOC_GEN_1, SOC_SL1,
    MAKE_TX_EQ_LIST_COMPACT(MAKE_TX_EQ_SOCKET0_DIE0_EACH_LANES_COMPACT(),
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane  0
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane  1
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane  2
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane  3
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane  4
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane  5
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane  6
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane  7
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane  8
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane  9
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane 10
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane 11
        MAKE_TX_EQ_LANE_DATA( 35, 20,  0 ), // lane 12
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane 13
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane 14
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane 15
    ),
    MAKE_TX_EQ_LIST_COMPACT(MAKE_TX_EQ_SOCKET0_DIE1_EACH_LANES_COMPACT(),
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane  0
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane  1
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane  2
        MAKE_TX_EQ_LANE_DATA( 31, 36,  0 ), // lane  3
        MAKE_TX_EQ_LANE_DATA( 32, 28,  4 ), // lane  4
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane  5
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane  6
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane  7
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane  8
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane  9
        MAKE_TX_EQ_LANE_DATA( 31, 36,  0 ), // lane 10
        MAKE_TX_EQ_LANE_DATA( 32, 28,  4 ), // lane 11
        MAKE_TX_EQ_LANE_DATA( 31, 36,  0 ), // lane 12
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane 13
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane 14
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane 15
    ),
    MAKE_TX_EQ_LIST_COMPACT(MAKE_TX_EQ_SOCKET0_DIE2_EACH_LANES_COMPACT(),
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane  0
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane  1
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane  2
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane  3
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane  4
        MAKE_TX_EQ_LANE_DATA( 32, 28,  4 ), // lane  5
        MAKE_TX_EQ_LANE_DATA( 31, 32,  4 ), // lane  6
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane  7
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane  8
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane  9
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane 10
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane 11
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane 12
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane 13
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane 14
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane 15
    ),
    MAKE_TX_EQ_LIST_COMPACT(MAKE_TX_EQ_SOCKET0_DIE3_EACH_LANES_COMPACT(),
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane  0
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane  1
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane  2
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane  3
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane  4
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane  5
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane  6
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane  7
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane  8
        MAKE_TX_EQ_LANE_DATA( 32, 28,  4 ), // lane  9
        MAKE_TX_EQ_LANE_DATA( 32, 28,  4 ), // lane 10
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane 11
        MAKE_TX_EQ_LANE_DATA( 31, 36,  0 ), // lane 12
        MAKE_TX_EQ_LANE_DATA( 32, 28,  4 ), // lane 13
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane 14
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane 15
    ),
    MAKE_TX_EQ_LIST_COMPACT(MAKE_TX_EQ_SOCKET1_DIE0_EACH_LANES_COMPACT(),
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane  0
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane  1
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane  2
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane  3
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane  4
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane  5
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane  6
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane  7
        MAKE_TX_EQ_LANE_DATA( 34, 24,  0 ), // lane  8
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane  9
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane 10
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane 11
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane 12
        MAKE_TX_EQ_LANE_DATA( 34, 24,  0 ), // lane 13
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane 14
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane 15
    ),
    MAKE_TX_EQ_LIST_COMPACT(MAKE_TX_EQ_SOCKET1_DIE1_EACH_LANES_COMPACT(),
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane  0
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane  1
        MAKE_TX_EQ_LANE_DATA( 31, 36,  0 ), // lane  2
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane  3
        MAKE_TX_EQ_LANE_DATA( 33, 24,  4 ), // lane  4
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane  5
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane  6
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane  7
        MAKE_TX_EQ_LANE_DATA( 31, 36,  0 ), // lane  8
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane  9
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane 10
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane 11
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane 12
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane 13
        MAKE_TX_EQ_LANE_DATA( 31, 36,  0 ), // lane 14
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane 15
    ),
    MAKE_TX_EQ_LIST_COMPACT(MAKE_TX_EQ_SOCKET1_DIE2_EACH_LANES_COMPACT(),
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane  0
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane  1
        MAKE_TX_EQ_LANE_DATA( 31, 28,  8 ), // lane  2
        MAKE_TX_EQ_LANE_DATA( 34, 24,  0 ), // lane  3
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane  4
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane  5
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane  6
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane  7
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane  8
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane  9
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane 10
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane 11
        MAKE_TX_EQ_LANE_DATA( 31, 36,  0 ), // lane 12
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane 13
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane 14
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane 15
    ),
    MAKE_TX_EQ_LIST_COMPACT(MAKE_TX_EQ_SOCKET1_DIE3_EACH_LANES_COMPACT(),
        MAKE_TX_EQ_LANE_DATA( 32, 28,  4 ), // lane  0
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane  1
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane  2
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane  3
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane  4
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane  5
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane  6
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane  7
        MAKE_TX_EQ_LANE_DATA( 34, 24,  0 ), // lane  8
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane  9
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane 10
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane 11
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane 12
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane 13
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane 14
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane 15
    ),
),
SL1_MAKE_TX_EQ_FREQ_TABLE_COMPACT(XGMI_TX_EQ_SPEED_96, SOC_GEN_2, SOC_SL1,
    MAKE_TX_EQ_LIST_COMPACT(MAKE_TX_EQ_SOCKET0_DIE0_EACH_LANES_COMPACT(),
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane  0
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane  1
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane  2
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane  3
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane  4
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane  5
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane  6
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane  7
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane  8
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane  9
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane 10
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane 11
        MAKE_TX_EQ_LANE_DATA( 35, 20,  0 ), // lane 12
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane 13
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane 14
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ) // lane 15
    ),
    MAKE_TX_EQ_LIST_COMPACT(MAKE_TX_EQ_SOCKET0_DIE1_EACH_LANES_COMPACT(),
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane  0
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane  1
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane  2
        MAKE_TX_EQ_LANE_DATA( 31, 36,  0 ), // lane  3
        MAKE_TX_EQ_LANE_DATA( 32, 28,  4 ), // lane  4
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane  5
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane  6
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane  7
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane  8
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane  9
        MAKE_TX_EQ_LANE_DATA( 31, 36,  0 ), // lane 10
        MAKE_TX_EQ_LANE_DATA( 32, 28,  4 ), // lane 11
        MAKE_TX_EQ_LANE_DATA( 31, 36,  0 ), // lane 12
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane 13
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane 14
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ) // lane 15
    ),
    MAKE_TX_EQ_LIST_COMPACT(MAKE_TX_EQ_SOCKET0_DIE2_EACH_LANES_COMPACT(),
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane  0
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane  1
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane  2
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane  3
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane  4
        MAKE_TX_EQ_LANE_DATA( 32, 28,  4 ), // lane  5
        MAKE_TX_EQ_LANE_DATA( 31, 32,  4 ), // lane  6
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane  7
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane  8
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane  9
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane 10
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane 11
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane 12
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane 13
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane 14
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ) // lane 15
    ),
    MAKE_TX_EQ_LIST_COMPACT(MAKE_TX_EQ_SOCKET0_DIE3_EACH_LANES_COMPACT(),
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane  0
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane  1
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane  2
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane  3
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane  4
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane  5
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane  6
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane  7
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane  8
        MAKE_TX_EQ_LANE_DATA( 32, 28,  4 ), // lane  9
        MAKE_TX_EQ_LANE_DATA( 32, 28,  4 ), // lane 10
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane 11
        MAKE_TX_EQ_LANE_DATA( 31, 36,  0 ), // lane 12
        MAKE_TX_EQ_LANE_DATA( 32, 28,  4 ), // lane 13
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane 14
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ) // lane 15
    ),
    MAKE_TX_EQ_LIST_COMPACT(MAKE_TX_EQ_SOCKET1_DIE0_EACH_LANES_COMPACT(),
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane  0
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane  1
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane  2
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane  3
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane  4
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane  5
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane  6
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane  7
        MAKE_TX_EQ_LANE_DATA( 34, 24,  0 ), // lane  8
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane  9
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane 10
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane 11
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane 12
        MAKE_TX_EQ_LANE_DATA( 34, 24,  0 ), // lane 13
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane 14
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ) // lane 15
    ),
    MAKE_TX_EQ_LIST_COMPACT(MAKE_TX_EQ_SOCKET1_DIE1_EACH_LANES_COMPACT(),
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane  0
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane  1
        MAKE_TX_EQ_LANE_DATA( 31, 36,  0 ), // lane  2
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane  3
        MAKE_TX_EQ_LANE_DATA( 33, 24,  4 ), // lane  4
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane  5
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane  6
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane  7
        MAKE_TX_EQ_LANE_DATA( 31, 36,  0 ), // lane  8
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane  9
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane 10
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane 11
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane 12
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane 13
        MAKE_TX_EQ_LANE_DATA( 31, 36,  0 ), // lane 14
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ) // lane 15
    ),
    MAKE_TX_EQ_LIST_COMPACT(MAKE_TX_EQ_SOCKET1_DIE2_EACH_LANES_COMPACT(),
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane  0
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane  1
        MAKE_TX_EQ_LANE_DATA( 31, 28,  8 ), // lane  2
        MAKE_TX_EQ_LANE_DATA( 34, 24,  0 ), // lane  3
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane  4
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane  5
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane  6
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane  7
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane  8
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane  9
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane 10
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane 11
        MAKE_TX_EQ_LANE_DATA( 31, 36,  0 ), // lane 12
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane 13
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane 14
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ) // lane 15
    ),
    MAKE_TX_EQ_LIST_COMPACT(MAKE_TX_EQ_SOCKET1_DIE3_EACH_LANES_COMPACT(),
        MAKE_TX_EQ_LANE_DATA( 32, 28,  4 ), // lane  0
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane  1
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane  2
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane  3
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane  4
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane  5
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane  6
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane  7
        MAKE_TX_EQ_LANE_DATA( 34, 24,  0 ), // lane  8
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane  9
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane 10
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane 11
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane 12
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ), // lane 13
        MAKE_TX_EQ_LANE_DATA( 32, 32,  0 ), // lane 14
        MAKE_TX_EQ_LANE_DATA( 33, 28,  0 ) // lane 15
    ),
),
